### ISSUE TITLE
KeyError: 'titlecontent' when running train_and_predict.py

### ISSUE THREAD

**Issue by mkorvas** [jeroendecroos/kaggle_transfer_learning_on_stack_exchange_tags#16]
I lost track of how to use the code. Now I managed to get to the point when `train_and_predict.py` no longer fails because of missing data or NLTK resources (and updated the `Makefile` and `README` with the corresponding instructions) but the train-and-predict script fails for me with a message like this:

    :; ./models/train_and_predict.py
    INFO:root:started at 20:30:36
    INFO:root:loading the data
    INFO:root:data loaded
    INFO:root:creating predictor
    INFO:root:predictor created
    INFO:root:started cross-validation testing
    INFO:root:evaluating on robotics
    INFO:root:creating train set
    INFO:root:train set created
    INFO:root:learning on the train set
    start fitting
    get features
    Traceback (most recent call last):
    File "/home/matej/.virtualenvs/kaggle_transfer_learning_on_stack_exchange_tags/lib/python3.5/site-packages/pandas/indexes/base.py", line 2134, in get_loc
        return self._engine.get_loc(key)
    File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
    File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
    File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
    File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
    KeyError: 'titlecontent'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "./models/train_and_predict.py", line 107, in <module>
        main()
    File "./models/train_and_predict.py", line 63, in timed_fun
        returns = fun(*args, **kwargs)
    File "./models/train_and_predict.py", line 102, in main
        cross_validate(predictor, train_data_frames)
    File "./models/train_and_predict.py", line 88, in cross_validate
        result = cross_validation.cross_validate(predictor, train_data_frames)
    File "/home/matej/akce/2017/01-kaggle-se/code/src/room007/eval/cross_validation.py", line 51, in cross_validate
        learner.fit(train_dataset)
    File "/home/matej/akce/2017/01-kaggle-se/code/src/room007/models/word_tag_predictor.py", line 145, in fit
        self._fit(train_data)
    File "/home/matej/akce/2017/01-kaggle-se/code/src/room007/models/word_tag_predictor.py", line 171, in _fit
        self.feature_creator.fit(train_data)
    File "/home/matej/akce/2017/01-kaggle-se/code/src/room007/models/word_tag_predictor.py", line 30, in fit
        self._train_tf_idf_vectorizer(train_data)
    File "/home/matej/akce/2017/01-kaggle-se/code/src/room007/models/word_tag_predictor.py", line 81, in _train_tf_idf_vectorizer
        self.tf_idf_vectorizer.fit(data['titlecontent'])
    File "/home/matej/.virtualenvs/kaggle_transfer_learning_on_stack_exchange_tags/lib/python3.5/site-packages/pandas/core/frame.py", line 2059, in __getitem__
        return self._getitem_column(key)
    File "/home/matej/.virtualenvs/kaggle_transfer_learning_on_stack_exchange_tags/lib/python3.5/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
        return self._get_item_cache(key)
    File "/home/matej/.virtualenvs/kaggle_transfer_learning_on_stack_exchange_tags/lib/python3.5/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
        values = self._data.get(item)
    File "/home/matej/.virtualenvs/kaggle_transfer_learning_on_stack_exchange_tags/lib/python3.5/site-packages/pandas/core/internals.py", line 3543, in get
        loc = self.items.get_loc(item)
    File "/home/matej/.virtualenvs/kaggle_transfer_learning_on_stack_exchange_tags/lib/python3.5/site-packages/pandas/indexes/base.py", line 2136, in get_loc
        return self._engine.get_loc(self._maybe_cast_indexer(key))
    File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
    File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
    File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
    File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
    KeyError: 'titlecontent'

...and it seems quite expected -- the data do not have such a column. Where should it be coming from?

**Comment by mkorvas** [comment]
I will assume that `train_and_predict.py` is no longer meant to be working standalone.

**Comment by jeroendecroos** [comment]
So this train_and_predict was reduced to not do any preprocessing anymore on the fly.
Because I didn't like that, I created the advanced_train_and_predict.py that does do some preprocessing on the fly.   (+ running a few times with different parameters)
